apiVersion: v1
kind: ConfigMap
metadata:
  name: cuppa-finance-stats-config
  labels:
    app: finance-stats
data:
  PORT: "3031"
  FASTIFY_ADDRESS: "0.0.0.0"
  CORS: "http://localhost:3500,https://app.fallensoulmonk.org,http://localhost:4541"
