apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-stats
  labels:
    app: finance-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-stats
  template:
    metadata:
      labels:
        app: finance-stats
    spec:
      containers:
        - name: cuppa-finance-stats
          image: cuppa/finance-stats:v12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3031
          envFrom:
            - configMapRef:
                name: cuppa-finance-stats-config
            - secretRef:
                name: finance-stats-secret
---
apiVersion: v1
kind: Service
metadata:
  name: finance-stats
  labels:
    app: finance-stats
spec:
  type: NodePort
  ports:
    - port: 3031
      nodePort: 32031
  selector:
    app: finance-stats
