apiVersion: v1
kind: Secret
metadata:
  name: finance-stats-secret
  labels:
    app: finance-stats
type: Opaque
data:
  POSTGRESQL_CONNECTION_STRING: cG9zdGdyZXM6Ly9jdXBwYTpwYXNzd29yZEBwb3N0Z3Jlcy9jdXBwYS1maW5hbmNlLXN0YXRzCg==
  REDIS_CONNECTION_STRING: cmVkaXM6Ly9yZWRpczo2Mzc5Cg==
  JWT_SECRET: c2VjcmV0Cg==
