version: '3.2'

services:
  cuppa-auth:
    image: cuppa-auth:latest
    env_file:
      - local.env
    environment:
      - PORT=3030
      - FASTIFY_PORT=3030
      - POSTGRESQL_CONNECTION_STRING=postgres://cuppa:toor@postgres/cuppa-authentication
    networks:
      - cuppa-network
    expose:
      - 3030
    ports:
      - 3030:3030

  finance-stats:
#    build: .
#    image: dev-finance-stats
    image: cuppa-finance-stats:latest
    networks:
      - cuppa-network
    env_file:
      - local.env
    environment:
      - PORT=3031
      - FASTIFY_PORT=3031
      - POSTGRESQL_CONNECTION_STRING=postgres://cuppa:toor@postgres/cuppa-finance-stats
      - REDIS_CONNECTION_STRING=redis://redis:6379
    expose:
      - 3031
    ports:
      - 3031:3031
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules

networks:
  cuppa-network:
    external:
      name: "cuppa-network"
