apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: cuppa-auth
          image: cuppa/auth:v9
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3030
              name: web
              protocol: TCP
          readinessProbe:
            httpGet:
              port: web
              path: /status
          envFrom:
            - configMapRef:
                name: cuppa-auth-config
            - secretRef:
                name: cuppa-auth-secret
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cuppa-auth
  labels:
    app: auth
spec:
  type: NodePort
  ports:
    - port: 3030
      nodePort: 32030
  selector:
    app: auth
